# Site settings
title: georgos blog
email: 
description: "A day in a life of a saddle point."
baseurl: ""
url: "http://georgosgeorgos.github.io"
twitter_username: georgosgeorgos
github_username:  georgosgeorgos

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
